### ISSUE TITLE
What is the difference between dreambooth and this finetuning example?

### ISSUE THREAD

**Issue by universewill** [LambdaLabsML/examples#11]
Dreambooth is also doing finetuning with stable diffusion, what is the difference between dreambooth and this finetuning example?

Dreambooth:
https://github.com/XavierXiao/Dreambooth-Stable-Diffusion

**Comment by justinpinkney** [comment]
There are two main differences:

1. Dreambooth associates a new token with the fine tuning dataset so that you can specifically generate that object/style
2. It does regularisation to preserve much of the original capability of the model

I guess the aim of my approach is to make the model generate absolutely everything in pokemon style. Whereas dream booth just wants to be able to make the model create things in that style when you add "in a <special token> style". I do think the two could be combined though.
